Привет, меня зовут Артем Носенко и я буду проверять твой проект.
<br>Небольшая вступительная часть и начнем работу)
<br> Если не против, то предлагаю общаться на «ты». Если это не удобно - дай знать, и мы перейдем на "вы". Моя основная цель — не указать на совершенные ошибки, а поделиться своим опытом и помочь сделать твой проект лучше. Для этого я буду использовать разный стиль оформления комментариев.
<div class="alert alert-block alert-success">
✔️ Все хорошо.
</div>

<div class="alert alert-warning">
⚠️ Критических замечаний нет, но есть возможность сделать твою работу лучше.
</div>

<div class="alert alert-block alert-danger">
❌ Если требуются исправления. Работа не может быть принята с красными комментариями.
</div>


Давай работать над проектом в диалоге: если ты что-то меняешь в проекте по моим рекомендациям — пиши об этом.
Будет очень хорошо, если ты будешь помечать свои действия следующим образом:
<div class="alert alert-block alert-info">
<b>Комментарий студента:</b> ...
</div>
Пожалуйста, не перемещай, не изменяй и не удаляй мои комментарии. Всё это поможет выполнить повторную проверку твоего проекта оперативнее».

In [3]:
# !pip install torchinfo

In [ ]:
import importlib
import src

from src.data_utils import text_clean
from src.next_token_dataset import next_token_dataset
from src.lstm_model import next_token_model
from src.lstm_train import train_model
from src.eval_transformer_pipeline import transformer_generator

In [9]:
importlib.reload(src.data_utils)
importlib.reload(src.next_token_dataset)
importlib.reload(src.lstm_model)
importlib.reload(src.lstm_train)

from src.data_utils import text_clean
from src.next_token_dataset import next_token_dataset
from src.lstm_model import next_token_model
from src.lstm_train import train_model
from src.eval_transformer_pipeline import transformer_generator

In [10]:
import pandas as pd
import yaml
import evaluate
import torch
from torchinfo import summary
import torch.nn as nn
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer
from tqdm.auto import tqdm

rouge = evaluate.load("rouge")

## Config

In [11]:
batch_size = 64
num_epochs = 5
min_len = 5
max_len = 10
tokenizer_model_name = "bert-base-uncased"
embedding_size = 128
hidden_dim = 256

config_path = "main_config"

# with open(f"configs/{config_path}.yaml", "r", encoding="utf-8") as file:
#     config = yaml.safe_load(file)
#     globals().update(config)

In [12]:
tokenizer = AutoTokenizer.from_pretrained(tokenizer_model_name)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

## Data preprocessing

In [397]:
texts = pd.read_csv("data/tweets.txt", engine='python', sep="±±±", header=None, names=["text"])
texts.head()

                                                text
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1  is upset that he can't update his Facebook by ...
2  @Kenichan I dived many times for the ball. Man...
3     my whole body feels itchy and like its on fire
4  @nationwideclass no, it's not behaving at all....

In [398]:
texts["text"] = texts["text"].apply(text_clean)
texts.head()

                                                text
0  awww that s a bummer you shoulda got david car...
1  is upset that he can t update his facebook by ...
2  i dived many times for the ball managed to sav...
3     my whole body feels itchy and like its on fire
4  no it s not behaving at all i m mad why am i h...

In [399]:
train_texts, val_test_texts = train_test_split(texts, test_size=0.2, random_state=42)
val_texts, test_texts = train_test_split(val_test_texts, test_size=0.5, random_state=42)

train_texts = train_texts.reset_index(drop=True)
val_texts = val_texts.reset_index(drop=True)
test_texts = test_texts.reset_index(drop=True)

train_texts.to_csv("data/train.csv", index=False)
val_texts.to_csv("data/val.csv", index=False)
test_texts.to_csv("data/test.csv", index=False)

print(f"Train sample size: {len(train_texts)}")
print(f"Validate sample size: {len(val_texts)}")
print(f"Test sample size: {len(test_texts)}")

Train sample size: 1280398
Validate sample size: 160050
Test sample size: 160050

## Loading from csv

In [13]:
train_dataset, _ = next_token_dataset(tokenizer, min_len=min_len, max_len=max_len).read_csv("data/train.csv", nrows=100000)
val_dataset, val_texts = next_token_dataset(tokenizer, min_len=min_len, max_len=max_len).read_csv("data/val.csv", nrows=10000)

train_loader = train_dataset.get_data_loader(batch_size=batch_size, shuffle=True)
val_loader = val_dataset.get_data_loader(batch_size=batch_size, shuffle=False)


print(f"Train dataset size: {len(train_dataset)}")
print(f"Validate dataset size: {len(val_dataset)}")
# # print(f"Test dataset size: {len(test_dataset)}")

0it [00:00, ?it/s]

  0%|          | 0/9976 [00:00<?, ?it/s]

  0%|          | 0/9975 [00:00<?, ?it/s]

  0%|          | 0/9979 [00:00<?, ?it/s]

  0%|          | 0/9976 [00:00<?, ?it/s]

  0%|          | 0/9985 [00:00<?, ?it/s]

  0%|          | 0/9973 [00:00<?, ?it/s]

  0%|          | 0/9976 [00:00<?, ?it/s]

  0%|          | 0/9976 [00:00<?, ?it/s]

  0%|          | 0/9979 [00:00<?, ?it/s]

  0%|          | 0/9985 [00:00<?, ?it/s]

0it [00:00, ?it/s]

  0%|          | 0/9976 [00:00<?, ?it/s]

Train dataset size: 1176608
Validate dataset size: 117458

## Model training

In [14]:
model = next_token_model(
    tokenizer=tokenizer,
    max_len=max_len,
    emb_dim=embedding_size,
    hidden_dim=hidden_dim,
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
print(f"Модель перенесена на девайс: {device}")
if torch.cuda.is_available():
  print(f"Девайс: {torch.cuda.get_device_name(0)}")

print("\nСводка по модели")
print(summary(model))

Модель перенесена на девайс: cpu

Сводка по модели
=================================================================
Layer (type:depth-idx)                   Param #
=================================================================
next_token_model                         --
├─Embedding: 1-1                         3,906,816
├─LSTM: 1-2                              395,264
├─LayerNorm: 1-3                         512
├─Dropout: 1-4                           --
├─Linear: 1-5                            7,844,154
=================================================================
Total params: 12,146,746
Trainable params: 12,146,746
Non-trainable params: 0
=================================================================

In [83]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-5)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, 'min')

train_model(
    num_epochs = num_epochs,
    train_loader = train_loader,
    val_texts = val_texts,
    val_loader = val_loader,
    model = model,
    criterion = criterion,
    optimizer = optimizer,
    scheduler = scheduler,
    save_model_every_epoch = True,
    config_path = config_path,
)

  0%|          | 0/18385 [00:00<?, ?it/s]

/Users/emc2/Проекты/личное/Практикум/Deep learning Engineer/dle_practicum/Sprint 2/Project/src/next_token_dataset.py:28: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  texts = [torch.tensor(item[0]) for item in batch]

Epoch 1/5 - train loss: 6.2043, val loss: 5.6962, val acc: 17.18%, val rouge1: 0.0057, val rouge2: 0.0003, lr: 0.0001
Модель сохранена в: models/main_config_1774188008__state_dict

  0%|          | 0/18385 [00:00<?, ?it/s]

Epoch 2/5 - train loss: 5.5712, val loss: 5.5038, val acc: 18.32%, val rouge1: 0.0125, val rouge2: 0.0004, lr: 0.0001
Модель сохранена в: models/main_config_1774206295__state_dict

  0%|          | 0/18385 [00:00<?, ?it/s]

Epoch 3/5 - train loss: 5.3822, val loss: 5.4178, val acc: 18.94%, val rouge1: 0.0113, val rouge2: 0.0007, lr: 0.0001
Модель сохранена в: models/main_config_1774240527__state_dict

  0%|          | 0/18385 [00:00<?, ?it/s]

Epoch 4/5 - train loss: 5.2648, val loss: 5.3665, val acc: 19.30%, val rouge1: 0.0171, val rouge2: 0.0009, lr: 0.0001
Модель сохранена в: models/main_config_1774249945__state_dict

  0%|          | 0/18385 [00:00<?, ?it/s]

Epoch 5/5 - train loss: 5.1763, val loss: 5.3322, val acc: 19.63%, val rouge1: 0.0183, val rouge2: 0.0010, lr: 0.0001
Модель сохранена в: models/main_config_1774251116__state_dict

In [11]:
model_path = f"models/{config_path}_{int(datetime.now().timestamp())}__state_dict"
torch.save(model.state_dict(), model_path)
print(f"Модель сохранена в: {model_path}")

Модель сохранена в: models/main_config_1774110199__state_dict

In [ ]:
tweet_idx = 0
tweet = val_texts["text"][tweet_idx]
predict = model.complete_tweet(val_texts["text"][tweet_idx])[0]

tweet_tokenized = tokenizer.encode(tweet)
length = int(len(tweet_tokenized) * 3 / 4)
tokens_to_generate = int(len(tweet_tokenized) * 1 / 4)
subtweet = tokenizer.decode(tweet_tokenized[:length], skip_special_tokens=True)

rouges = model.compute_rouges(val_texts.iloc[tweet_idx:tweet_idx+1])

print(f"Tweet:    {tweet}")
print(f"Subtweet: {subtweet}")
print(f"Predict:  {predict}")
print(f'Rouges:   {rouges}')

Tweet:    nice hair cut dude why were your students leaving in the middle of class 1st period
Subtweet: nice hair cut dude why were your students leaving in the middle
Predict:  nice hair cut dude why were your students leaving in the middle week
Rouges:   (np.float64(0.0), np.float64(0.0))

In [85]:
for tweet_idx in tqdm(range(0,1000)):
    tweet = val_texts["text"][tweet_idx]
    predict = model.complete_tweet(val_texts["text"][tweet_idx])[0]

    tweet_tokenized = tokenizer.encode(tweet)
    length = int(len(tweet_tokenized) * 3 / 4)
    tokens_to_generate = int(len(tweet_tokenized) * 1 / 4)
    subtweet = tokenizer.decode(tweet_tokenized[:length], skip_special_tokens=True)

    rouges = model.compute_rouges(val_texts.iloc[tweet_idx:tweet_idx+1])
    if rouges[0] >= 0.7:
        print(f"Tweet:    {tweet}")
        print(f"Subtweet: {subtweet}")
        print(f"Predict:  {predict}")
        print(f'Rouges:   {rouges}')
        break

  0%|          | 0/1000 [00:00<?, ?it/s]

Tweet:    seb day
Subtweet: seb
Predict:  seb day
Rouges:   (np.float64(1.0), np.float64(0.0))

## distilgpt2

In [71]:
model_name = "distilgpt2"
tweet_idx = 4
tweet = val_texts["text"][tweet_idx]
tr = transformer_generator(model_name)

tweet_start, _, tweet_tokenized = tr.slice_tweet(tweet)
predict = tr.complete_tweet(tweet)
rouges = tr.compute_rouges(val_texts.iloc[tweet_idx:tweet_idx+1])

print(f"Tweet:    {tweet}")
print(f"Subtweet: {tweet_start}")
print(f"Predict:  {predict}")
print(f"Rouges:   {rouges}")

  0%|          | 0/1 [00:00<?, ?it/s]

Tweet:    hates payer contracts wasted energy or not it s true looks like it s going to be a long work day
Subtweet: hates payer contracts wasted energy or not it s true looks like it s going
Predict:  hates payer contracts wasted energy or not it s true looks like it s going to be a big deal,
Rouges:   (np.float64(0.2), np.float64(0.0))

In [69]:
tr.compute_rouges(val_texts)

  0%|          | 0/9976 [00:00<?, ?it/s]

(np.float64(0.058353121042767256), np.float64(0.0057982584220555335))

<b>Комментарий от ревьюера v1</b>
<div class="alert alert-block alert-danger">
❌ Стоит добавить выводы и сравнение distilgpt2 и LSTM. Так мы поймем какой алгоритм лучше работает.
</div>

<b>Комментарий от ревьюера v1</b>


    
# Общий вывод

<div class="alert alert-block alert-success">
    

Спасибо за работу, у тебя получился отличный проект!\
Я готов принять твой проект после добавления выводов.\
Если есть вопросы или желание улучшить твой проект - оставь вопросы комментарии после этой ячейки. Постараюсь тебе помочь с ответами и улучшением твоего проекта! 
</div>

<div class="alert alert-block alert-info">
<b>Комментарий студента:</b> Артём, привет! Спасибо за обратную связь! Сейчас всё сделаем :)
</div>

## Правки

In [33]:
lstmka = next_token_model(
    tokenizer=tokenizer,
    max_len=max_len,
    emb_dim=embedding_size,
    hidden_dim=hidden_dim,
)
lstmka.load_state_dict(torch.load("models/main_config_1774114111__state_dict", weights_only=True, map_location=torch.device('cpu')))
llmka = transformer_generator("distilgpt2")

In [34]:
tweet_idx = 4
tweet = val_texts["text"][tweet_idx]

tweet_start, _, tweet_tokenized = llmka.slice_tweet(tweet)

lstm_predict = lstmka.complete_tweet(tweet)[0]
lstm_rouges = lstmka.compute_rouges(val_texts.iloc[tweet_idx:tweet_idx+1])
    
llm_predict = llmka.complete_tweet(tweet)
llm_rouges = llmka.compute_rouges(val_texts.iloc[tweet_idx:tweet_idx+1])


print(f"Tweet:         {tweet}")
print(f"Subtweet:      {tweet_start}")
print(f"LSTM predict:  {lstm_predict}")
print(f"LLM predict:   {llm_predict}")
print("-"*10)
print(f"LSTM ROUGE1: {lstm_rouges[0]:.4f} / ROUGE2: {lstm_rouges[1]:.4f}")
print(f"LLM  ROUGE1: {llm_rouges[0]:.4f} / ROUGE2: {llm_rouges[1]:.4f}")

  0%|          | 0/1 [00:00<?, ?it/s]

Tweet:         hates payer contracts wasted energy or not it s true looks like it s going to be a long work day
Subtweet:      hates payer contracts wasted energy or not it s true looks like it s going
LSTM predict:  hates payer contracts wasted energy or not it s true looks like it s going to it s a lot of fun
LLM predict:   hates payer contracts wasted energy or not it s true looks like it s going to be a bigger problem than
----------
LSTM ROUGE1: 0.2000 / ROUGE2: 0.0000
LLM  ROUGE1: 0.5000 / ROUGE2: 0.4000

In [35]:
%%time
lstm_rouges = lstmka.compute_rouges(val_texts)
print(f"LSTM ROUGE1: {lstm_rouges[0]:.4f} / ROUGE2: {lstm_rouges[1]:.4f}")

LSTM ROUGE1: 0.0392 / ROUGE2: 0.0027
CPU times: user 58.2 s, sys: 2.34 s, total: 1min
Wall time: 1min 1s

In [36]:
%%time
llm_rouges = llmka.compute_rouges(val_texts)
print(f"LLM  ROUGE1: {llm_rouges[0]:.4f} / ROUGE2: {llm_rouges[1]:.4f}")

  0%|          | 0/9976 [00:00<?, ?it/s]

LLM  ROUGE1: 0.0579 / ROUGE2: 0.0053
CPU times: user 11min 47s, sys: 37.1 s, total: 12min 24s
Wall time: 12min 27s

## Выводы
За небольшое время удалось обучить LSTM, которая показывает качество примерно в два раза хуже трансформера distilGPT2.
При это скорость LSTM в 10 раз выше трансформера.

LSTM больше пригоден для сервисов с высокими требованиями по latency и/или времени до первого токена, чем трансформеры.

Также LSTM, при условии удовлетворенности качеством, лучше использовать на мобильных устройствах

<div class="alert alert-block alert-info">
<b>Комментарий студента:</b> Что скажешь?
</div>